/** One user inside one room. */
export class Participant {
  constructor({ userId, username, role }) {
    this.userId = userId; // stable id generated by the browser (survives page refresh)
    this.username = username;
    this.role = role;
    this.socketId = null; // current socket connection (changes on reconnect)
    this.online = false;
    this.joinedAt = Date.now();
    this.disconnectTimer = null; // grace-period timer after a disconnect
  }

  connect(socketId) {
    this.socketId = socketId;
    this.online = true;
    this.clearDisconnectTimer();
  }

  disconnect() {
    this.socketId = null;
    this.online = false;
  }

  clearDisconnectTimer() {
    if (this.disconnectTimer) clearTimeout(this.disconnectTimer);
    this.disconnectTimer = null;
  }

  /** What we send to clients (never leak socket ids or timers). */
  toJSON() {
    return {
      userId: this.userId,
      username: this.username,
      role: this.role,
      online: this.online,
    };
  }
}
